runtime: python38 # or another supported version

instance_class: F1

env_variables:
  LOCAL: 'FALSE'
  MYSQL_USER: useradmin # please put in your credentials
  MYSQL_PASSWORD: test1234! # please put in your credentials
  MYSQL_DB: todolist # please put in your credentials
  MYSQL_HOST:  todolist2.database.windows.net # please put in your credentials
  MYSQL_SERVER: todolist1

handlers:
  # Matches requests to /images/... to files in static/images/...
  - url: /img
    static_dir: static/img

  - url: /script
    static_dir: static/script

  - url: /styles
    static_dir: static/styles
